### ISSUE TITLE
Using `Track.Map` on setup seems to crash leaderboard.

### ISSUE THREAD

**Issue by haixuanTao** [carla-simulator/leaderboard#144]
I'm trying to use `opendrive_map` sensors within the leaderboard by setting up:
```python
class Track(Enum):

    """
    This enum represents the different tracks of the CARLA AD leaderboard.
    """

    SENSORS = "SENSORS"
    MAP = "MAP"

class DoraAgent(AutonomousAgent):
    def setup(self, path_to_conf_file):
        """
        Setup the agent parameters
        """
        self.track = Track.MAP

    def sensors(self):  # pylint: disable=no-self-use
        """
        Define the sensor suite required by the agent
        return: a list containing the required sensors in the following format:
        [
        {'type': 'sensor.camera.rgb', 'x': 0.7, 'y': -0.4, 'z': 1.60, 'roll': 0.0, 'pitch': 0.0, 'yaw': 0.0,
        width': 300, 'height': 200, 'fov': 100, 'id': 'Left'},
        {'type': 'sensor.camera.rgb', 'x': 0.7, 'y': 0.4, 'z': 1.60, 'roll': 0.0, 'pitch': 0.0, 'yaw': 0.0,
        width': 300, 'height': 200, 'fov': 100, 'id': 'Right'},
        {'type': 'sensor.lidar.ray_cast', 'x': 0.7, 'y': 0.0, 'z': 1.60, 'yaw': 0.0, 'pitch': 0.0, 'roll': 0.0,
        id': 'LIDAR'}
        ]
        """
        sensors = []

        return sensors
```

But it seems that many scenario are skipped and the one that are not crash for some obscure `Track` issues when tested on leaderboard/data/routes_training and leaderboard/data/routes_devtest.

```bash
/home/peter/Documents/CONTRIB/dependencies/leaderboard/leaderboard/leaderboard_evaluator.py:87: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(dist.version) < LooseVersion('0.9.13'):

========= Preparing RouteScenario_0 (repetition 0) =========
> Loading the world
Skipping scenario 'ParkingExit_1' due to setup error: 'ParkingExit'
Skipping scenario 'SignalizedJunctionLeftTurn_1' due to setup error: 'SignalizedJunctionLeftTurn'
Skipping scenario 'NonSignalizedJunctionRightTurn_1' due to setup error: 'NonSignalizedJunctionRightTurn'
Skipping scenario 'Accident_1' due to setup error: 'Accident'
Skipping scenario 'NonSignalizedJunctionLeftTurn_1' due to setup error: 'NonSignalizedJunctionLeftTurn'
Skipping scenario 'ControlLoss_1' due to setup error: 'ControlLoss'
Skipping scenario 'ConstructionObstacleTwoWays_1' due to setup error: 'ConstructionObstacleTwoWays'
Skipping scenario 'OppositeVehicleTakingPriority_1' due to setup error: 'OppositeVehicleTakingPriority'
Skipping scenario 'NonSignalizedJunctionLeftTurn_2' due to setup error: 'NonSignalizedJunctionLeftTurn'
Skipping scenario 'NonSignalizedJunctionLeftTurn_3' due to setup error: 'NonSignalizedJunctionLeftTurn'
Skipping scenario 'AccidentTwoWays_2' due to setup error: 'AccidentTwoWays'
Skipping scenario 'OppositeVehicleTakingPriority_2' due to setup error: 'OppositeVehicleTakingPriority'
Skipping scenario 'OppositeVehicleTakingPriority_3' due to setup error: 'OppositeVehicleTakingPriority'
Skipping scenario 'ControlLoss_2' due to setup error: 'ControlLoss'
Skipping scenario 'ControlLoss_3' due to setup error: 'ControlLoss'
Skipping scenario 'ControlLoss_4' due to setup error: 'ControlLoss'
Skipping scenario 'HardBreakRoute_2' due to setup error: 'HardBreakRoute'
Skipping scenario 'OppositeVehicleRunningRedLight_1' due to setup error: 'OppositeVehicleRunningRedLight'
Skipping scenario 'ConstructionObstacle_2' due to setup error: 'ConstructionObstacle'
Skipping scenario 'VehicleOpensDoorTwoWays_1' due to setup error: 'VehicleOpensDoorTwoWays'
Skipping scenario 'OppositeVehicleRunningRedLight_2' due to setup error: 'OppositeVehicleRunningRedLight'
Skipping scenario 'HazardAtSideLane_2' due to setup error: 'HazardAtSideLane'
Skipping scenario 'VehicleTurningRoutePedestrian_1' due to setup error: 'VehicleTurningRoutePedestrian'
Skipping scenario 'ParkedObstacleTwoWays_1' due to setup error: 'ParkedObstacleTwoWays'
Skipping scenario 'DynamicObjectCrossing_1' due to setup error: 'DynamicObjectCrossing'
Skipping scenario 'OppositeVehicleTakingPriority_4' due to setup error: 'OppositeVehicleTakingPriority'
Skipping scenario 'ConstructionObstacleTwoWays_2' due to setup error: 'ConstructionObstacleTwoWays'
Skipping scenario 'BlockedIntersection_1' due to setup error: 'BlockedIntersection'
Skipping scenario 'HardBreakRoute_3' due to setup error: 'HardBreakRoute'
Skipping scenario 'HardBreakRoute_4' due to setup error: 'HardBreakRoute'
Skipping scenario 'ControlLoss_6' due to setup error: 'ControlLoss'
Skipping scenario 'DynamicObjectCrossing_2' due to setup error: 'DynamicObjectCrossing'
Skipping scenario 'BlockedIntersection_2' due to setup error: 'BlockedIntersection'
Skipping scenario 'InvadingTurn_1' due to setup error: 'InvadingTurn'
Skipping scenario 'OppositeVehicleTakingPriority_5' due to setup error: 'OppositeVehicleTakingPriority'
Skipping scenario 'ConstructionObstacleTwoWays_3' due to setup error: 'ConstructionObstacleTwoWays'
Skipping scenario 'BlockedIntersection_3' due to setup error: 'BlockedIntersection'
Skipping scenario 'AccidentTwoWays_2' due to setup error: 'AccidentTwoWays'
Skipping scenario 'NonSignalizedJunctionRightTurn_3' due to setup error: 'NonSignalizedJunctionRightTurn'
Skipping scenario 'VehicleTurningRoutePedestrian_2' due to setup error: 'VehicleTurningRoutePedestrian'
Skipping scenario 'DynamicObjectCrossing_3' due to setup error: 'DynamicObjectCrossing'
Skipping scenario 'VehicleTurningRoute_1' due to setup error: 'VehicleTurningRoute'
Skipping scenario 'ConstructionObstacle_2' due to setup error: 'ConstructionObstacle'
Skipping scenario 'ControlLoss_7' due to setup error: 'ControlLoss'
Skipping scenario 'HardBreakRoute_4' due to setup error: 'HardBreakRoute'
Skipping scenario 'OppositeVehicleRunningRedLight_3' due to setup error: 'OppositeVehicleRunningRedLight'
Skipping scenario 'PriorityAtJunction_1' due to setup error: 'PriorityAtJunction'
Skipping scenario 'HazardAtSideLane_3' due to setup error: 'HazardAtSideLane'
Skipping scenario 'HazardAtSideLane_4' due to setup error: 'HazardAtSideLane'
Skipping scenario 'HardBreakRoute_5' due to setup error: 'HardBreakRoute'
Skipping scenario 'ControlLoss_8' due to setup error: 'ControlLoss'
Skipping scenario 'VehicleTurningRoute_2' due to setup error: 'VehicleTurningRoute'
Skipping scenario 'DynamicObjectCrossing_4' due to setup error: 'DynamicObjectCrossing'
Skipping scenario 'InvadingTurn_2' due to setup error: 'InvadingTurn'
Skipping scenario 'NonSignalizedJunctionRightTurn_4' due to setup error: 'NonSignalizedJunctionRightTurn'
Skipping scenario 'InvadingTurn_3' due to setup error: 'InvadingTurn'
Skipping scenario 'NonSignalizedJunctionLeftTurn_4' due to setup error: 'NonSignalizedJunctionLeftTurn'
Skipping scenario 'ControlLoss_9' due to setup error: 'ControlLoss'
Skipping scenario 'ParkedObstacleTwoWays_2' due to setup error: 'ParkedObstacleTwoWays'
Skipping scenario 'DynamicObjectCrossing_5' due to setup error: 'DynamicObjectCrossing'
Skipping scenario 'InvadingTurn_4' due to setup error: 'InvadingTurn'
Skipping scenario 'OppositeVehicleTakingPriority_6' due to setup error: 'OppositeVehicleTakingPriority'
Skipping scenario 'InvadingTurn_5' due to setup error: 'InvadingTurn'
Skipping scenario 'HardBreakRoute_6' due to setup error: 'HardBreakRoute'
Skipping scenario 'HardBreakRoute_7' due to setup error: 'HardBreakRoute'
Skipping scenario 'BlockedIntersection_4' due to setup error: 'BlockedIntersection'
Skipping scenario 'ConstructionObstacleTwoWays_4' due to setup error: 'ConstructionObstacleTwoWays'
Skipping scenario 'HardBreakRoute_8' due to setup error: 'HardBreakRoute'
> Setting up the agent

The sensor's configuration used is invalid:

Traceback (most recent call last):
  File "/home/peter/Documents/CONTRIB/dependencies/leaderboard/leaderboard/leaderboard_evaluator.py", line 268, in _load_and_run_scenario
    validate_sensor_configuration(self.sensors, track, args.track)
  File "/home/peter/Documents/CONTRIB/dependencies/leaderboard/leaderboard/autoagents/agent_wrapper.py", line 63, in validate_sensor_configuration
    raise SensorConfigurationInvalid("You are submitting to the wrong track [{}]!".format(Track(selected_track)))
leaderboard.envs.sensor_interface.SensorConfigurationInvalid: You are submitting to the wrong track [Track.SENSORS]!
```

I am using:
Carla leaderboard 2.0 version
Leaderboard on `leaderboard-2.0` branch
Scenario Runner on `leaderboard-2.0` branch
Python 3.7.15

**Comment by Daraan** [comment]
How do you launch the leaderboard_evaluator.py? Did you set there the track *as well*?

I.e. if you use the `run_leaderboard.sh` file you need to change this line
```bash
export CHALLENGE_TRACK_CODENAME=MAP
```
for a direct call `leaderboard_evaluator.py --track=MAP`

**Comment by glopezdiest** [comment]
Closed as this was answered already
